# Instructor Guide {-}

The primary goal of this exercise is to get students comfortable interacting with the R console.  Students will complete several `swirl` lessons introducing basic R concepts, and then apply their new skills by conducting a brief exploration of a dataframe.

## Teaching Recommendations {-}

This exercise is designed to be used either

1. As a stand-alone "taste of R", to introduce students to the field of data science, give them an idea of what a data scientist's day-to-day work looks like, and help students see it as something they could do.
1. As an entry point for a more in-depth course or workshop.  In this case we recommend following up on important topics using additional resources (such as [R for Data Science](https://r4ds.had.co.nz/)).  The `swirl` lessons are great for letting students work through the basics in a "real" R environment where they get immediate feedback, but they are hard for students to refer back to later.  We find `swirl` most useful for giving students a first look at the big ideas, along with practice typing commands into the console.  This sets them up well for a more in-depth treatment over the subsequent course/workshop sessions.

The `swirl` lessons touch on several additional R commands and concepts beyond those mentioned in the learning objectives and provide a useful starting point for going deeper if you desire.  Additional `swirl` lessons can be found at the [swirl Course Network](http://swirlstats.com/scn/).

## Lesson Plan  {-}

| Activity | Time |
| :-- | :- |
| Introduction | 10 minutes |
| Setup | 25 minutes* |
| R Programming with `swirl` | 1 hr 40 minutes |
| Explore `us_contagious_diseases` dataframe | 20 minutes |
| *Optional Challenge Exercise*\*\* | *20 minutes* |
| Wrap-up | 5 minutes |

\*Student Setup:

  - Most students will not need the full time for setup, but we have built in some buffer for anyone who gets stuck.  Students can proceed with the exercises on their own once they have finished setting up.
  - Most of the setup steps can be completed ahead of time if desired.  We have provided a Pre-Lab with instructions in the Appendix.

\*\*Included under *Explore `us_contagious_diseases` dataframe*

## Computing Requirements {-}

- RStudio
- R packages
  - [`swirl`](https://cran.r-project.org/web/packages/swirl/index.html)
  - [`dplyr`](https://cran.r-project.org/web/packages/dplyr/index.html)
  - [`dslabs`](https://cran.r-project.org/web/packages/dslabs/index.html)

This book provides instructions on how to set these up in the cloud using the [AnVIL platform](https://anvil.terra.bio/), so that your students will not need to install anything.  Depending on your needs, you might decide to run this activity on a different cloud provider, such [Posit Cloud](https://posit.cloud/) (formerly RStudio Cloud), or have your students install RStudio themselves.

## Teaching on AnVIL

The AnVIL (Analysis Visualization and Informatics Lab-space) platform is a cloud computing platform specially designed for analyzing biological data, and is used by scientists doing all sorts of biological research.

AnVIl can be an excellent way to introduce students to biological data analysis and cloud computing.  Because all computation on AnVIL is done in the cloud, all students can use the exact same computing environment through their browsers, with no need for software installation or access to expensive computers.

If this is your first time using AnVIL (or first time using it for a course), the [AnVIL Instructor Guide](https://jhudatascience.org/AnVIL_Book_Instructor_Guide) provides a walkthrough of how to set up and teach a course or workshop on AnVIL.

### Checklist and Timeframe

Here is a [checklist](https://docs.google.com/document/d/1-HqQqH_qlkHwRua8-b92MyKQcEmcl0Nk37rSYqP49aw/edit) to help you keep track of the steps for setting up and teaching on AnVIL. Details about each of these steps can be found in the [AnVIL Instructor Guide](https://jhudatascience.org/AnVIL_Book_Instructor_Guide).  *Note that this checklist is written for workshop instructors as well as classroom instructors, so some of the "Event Setup" steps may not be applicable to you, depending on your teaching context.*

Here is a suggested timeframe for working through the checklist:

**1+ month before**

- Figure out how you will fund the class/workshop
- Start working through INSTRUCTOR SETUP.  It's a good idea to get billing figured out with plenty of time to spare
- Do any necessary EVENT SETUP steps

**1+ week before**

- Start working through RUNNING THE CLASS
- If possible, have students log in to AnVIL and send you their usernames, so you can add them to the Student Group ahead of time.  This saves time on the day of the class.
- **Do not add students to your Billing Project** ahead of time.  This prevents them from accruing costs.

**Day of (or shortly before)** 

- Add students to Billing Project
- Have students clone the Workspace (They cannot do this until you have added them to the Billing Project.  As soon as they do this, they can start computing.)

**After**

- Collect feedback, if you didn't do it during the class/workshop
- Work though EVENT WRAP-UP - until you shut things down, you will continue to accrue costs
