# Setup on AnVIL

Welcome!  This lab will introduce you to some basic data analysis using the [R programming language](https://www.r-project.org/).  In order to do this, there are a few steps you need to complete so that you can access the material.

## Set up Account

```{r, echo = FALSE, results='asis'}
cow::borrow_chapter(
  doc_path = "child/_child_student_create_account.Rmd",
  repo_name = "jhudsl/AnVIL_Template"
)
```

## Access Materials

```{r, echo = FALSE, results='asis'}
#workspace_name <- "Example_Workspace"
#workspace_link <- "http://example.com/"
billing_project <- "provided by your instructor"
cow::borrow_chapter(
  doc_path = "child/_child_student_workspace_clone.Rmd",
  branch = "student-clone",
  repo_name = "jhudsl/AnVIL_Template"
)
```

## Start RStudio

```{r, echo = FALSE, results='asis'}
AnVIL_module_settings <- list(
  audience = "student",
#   docker_image = "example docker image link",
  startup_script = "ask your instructor"
)
cow::borrow_chapter(
  doc_path = "child/_child_rstudio_launch.Rmd",
  repo_name = "jhudsl/AnVIL_Template"
)
```
